### ISSUE TITLE
PoetryProject reads files and dirs using iterdir() when looking for src dir

### ISSUE THREAD

**Issue by pdunne** [nahco314/poetry2rye#6]
Hi,

The current line in the PoetryProject class gets a list of files and directories, which causes an error for me on MacOS because of the inevitable .DS_Store file generated by Finder. 

-> it raises `ControlledError("multiple subdirectories found in src")`

https://github.com/nahco314/poetry2rye/blob/abf8b4f246ab128ba4e80cced202506aa47a8db8/src/poetry2rye/project.py#L114

However the following line should work to filter only dirs:

`sub_lst = [d for d in self.src_path.iterdir() if d.is_dir()]`

Thanks for the nice package.

Regards.

**Comment by nahco314** [comment]
Thank you for reporting the problem!
I'm too busy right now to get around to it and will address it in the next week or so.
If it is a simple change that can be fixed, you can create a PR and I can merge it.

**Comment by nahco314** [comment]
https://github.com/nahco314/poetry2rye/commit/9e67b6834ca57e0fb34e11e91ac1d553fec25336 will fix it!
If it still have problem, please re-open the issue.

**Comment by pdunne** [comment]
nice!

sorry I didn't see your update until now. Thanks for the change.

Regards.
